# DataSource配置
spring:
  datasource:
    url: jdbc:mysql://anno.coronadb.alibaba.net:3306/TRAFFIC_SIGNAL_APP
    username: TRAFFIC_SIGNAL_APP
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver


