spring:
  application:
    name: evo-springboot-2x

management:
  server:
    port: 7002
  endpoints:
    enabled-by-default: true

#  endpoints:
#    web:
#      exposure:
#        include: *
  endpoint:
    health:
      show-details: always

server:
  port: 7001
  # access log 日志开关
  tomcat:
    #日志输出目录，这里是设置为当前目录下
    basedir: /${user.home}/${spring.application.name}/logs
    accesslog:
      enabled: true
#      pattern: %h %l %u %t "%r" %s %b %D
      directory: /
  servlet:
    context-path: /


