management:
  server:
    port: 7002
  endpoints:
    enabled-by-default: true

#  endpoints:
#    web:
#      exposure:
#        include: *
  endpoint:
    health:
      show-details: always

# access log 日志开关

server:
  tomcat:
    access-log-enabled: true
    #日志格式
#    access-log-pattern: %h %l %u %t "%r" %s %b %D
    #日志输出目录，这里是设置为当前目录下
    basedir: ./


evo:
  module: springboot
  value: ${random.value}
  number: ${random.int}
  bignumber: ${random.long}
  test1: ${random.int(10)}
  test2: ${random.int[10,20]}

tazine:
  est: 2016
  employee[0]: 张三
  employee[1]: 李四
  employee[2]: 王五